"""add idempotency_key_hash to documents

Revision ID: 4de0fe2028b1
Revises: 18c2ebd46780
Create Date: 2026-08-18 16:44:35.488210

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4de0fe2028b1"
down_revision: str | Sequence[str] | None = "18c2ebd46780"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column("idempotency_key_hash", sa.String(length=64), nullable=True),
    )
    op.create_unique_constraint(None, "documents", ["idempotency_key_hash"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="unique")
    op.drop_column("documents", "idempotency_key_hash")
    # ### end Alembic commands ###
