"""add document_type and classification_confidence

Revision ID: 4f13cbf7329d
Revises: fa641746964a
Create Date: 2026-08-21 22:47:02.676438

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f13cbf7329d"
down_revision: Union[str, Sequence[str], None] = "fa641746964a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("document_type", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "documents", sa.Column("classification_confidence", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "classification_confidence")
    op.drop_column("documents", "document_type")
    # ### end Alembic commands ###
