"""add content_hash to documents

Revision ID: a564213e9d80
Revises: 4f13cbf7329d
Create Date: 2026-08-22 18:32:45.024140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a564213e9d80'
down_revision: Union[str, Sequence[str], None] = '4f13cbf7329d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content_hash')
    # ### end Alembic commands ###
