COUNTRIES: dict[str, dict[str, str | list[str]]] = {
    "IN": {
        "name": "India",
        "legislations": [
            "Indian Contract Act, 1872 — governs formation, performance, and breach of contracts",
            "Consumer Protection Act, 2019 — protects consumers against unfair trade practices, defective goods, and deficient services",
            "Information Technology Act, 2000 — governs electronic transactions, digital signatures, and cybercrime",
            "Indian Partnership Act, 1932 — governs rights and liabilities of partners in a firm",
            "Sale of Goods Act, 1930 — governs contracts for sale of goods, warranty, and condition terms",
            "Arbitration and Conciliation Act, 1996 — governs arbitration proceedings and enforcement of awards",
            "Companies Act, 2013 — governs formation, management, and dissolution of companies",
            "Negotiable Instruments Act, 1881 — governs promissory notes, bills of exchange, and cheques",
        ],
    },
    "US": {
        "name": "United States",
        "legislations": [
            "Uniform Commercial Code (UCC) — governs commercial transactions including sales, leases, and negotiable instruments",
            "Securities Exchange Act of 1934 — governs securities trading and disclosure requirements",
            "Sarbanes-Oxley Act (SOX) — governs corporate financial reporting and accountability",
            "Americans with Disabilities Act (ADA) — prohibits discrimination based on disability",
            "Fair Credit Reporting Act (FCRA) — regulates collection and use of consumer credit information",
            "Federal Arbitration Act (FAA) — governs enforcement of arbitration agreements",
            "State Contract Law — each state has its own contract law governs formation and enforcement",
            "Can-Spam Act — governs commercial email messages and opt-out requirements",
        ],
    },
    "UK": {
        "name": "United Kingdom",
        "legislations": [
            "UK Consumer Rights Act 2015 — consolidates consumer rights for goods, services, and digital content",
            "Companies Act 2006 — governs formation, management, and reporting of companies",
            "Employment Rights Act 1996 — governs employment contracts, dismissal, and redundancy",
            "Data Protection Act 2018 (UK GDPR) — governs processing of personal data",
            "Unfair Contract Terms Act 1977 — restricts use of exclusion and limitation clauses",
            "Sale of Goods Act 1979 — governs contracts for sale of goods",
            "Arbitration Act 1996 — governs arbitration proceedings in England and Wales",
            "Fraud Act 2006 — defines fraud offences including false representation",
        ],
    },
    "AE": {
        "name": "United Arab Emirates",
        "legislations": [
            "UAE Civil Transactions Law (Federal Law No. 5 of 1985) — governs contracts, obligations, and civil liability",
            "UAE Commercial Transactions Law (Federal Law No. 18 of 1993) — governs commercial contracts and business transactions",
            "UAE Labour Law (Federal Decree-Law No. 33 of 2021) — governs employment contracts, rights, and obligations",
            "UAE Personal Status Law (Federal Law No. 28 of 2005) — governs family and personal matters",
            "DIFC Arbitration Law — governs arbitration in the Dubai International Financial Centre",
            "ADGM Regulations — governs business and financial activities in Abu Dhabi Global Market",
            "UAE Data Protection Law (Federal Decree-Law No. 45 of 2021) — governs processing of personal data",
            "UAE Cybercrime Law (Federal Decree-Law No. 34 of 2021) — governs cybercrime offences",
        ],
    },
    "SG": {
        "name": "Singapore",
        "legislations": [
            "Singapore Contract Law — based on English common law governs formation and enforcement of contracts",
            "Companies Act (Cap. 50) — governs formation, management, and winding up of companies",
            "Employment Act (Cap. 91) — governs employment terms, conditions, and rights",
            "Personal Data Protection Act (PDPA) — governs collection, use, and disclosure of personal data",
            "Sale of Goods Act (Cap. 393) — governs contracts for sale of goods",
            "Unfair Contract Terms Act (Cap. 396) — restricts unfair exclusion and limitation clauses",
            "International Arbitration Act (Cap. 143A) — governs international arbitration proceedings",
            "Payment Services Act 2019 — governs payment services and digital payment token services",
        ],
    },
    "AU": {
        "name": "Australia",
        "legislations": [
            "Australian Consumer Law (ACL) — governs consumer rights, product safety, and fair trading",
            "Corporations Act 2001 — governs company registration, management, and deregistration",
            "Competition and Consumer Act 2010 — governs competition, consumer protection, and regulatory frameworks",
            "Privacy Act 1988 — governs collection, use, and disclosure of personal information",
            "Electronic Transactions Act 1999 — validates electronic transactions and communications",
            "Sale of Goods Act (varies by state) — governs contracts for sale of goods",
            "Commercial Arbitration Acts — governs arbitration proceedings in each state and territory",
            "Modern Slavery Act 2018 — requires reporting on modern slavery risks in supply chains",
        ],
    },
    "CA": {
        "name": "Canada",
        "legislations": [
            "Canada Business Corporations Act (CBCA) — governs federal corporations",
            "Provincial Securities Acts — governs securities trading and disclosure in each province",
            "Personal Information Protection and Electronic Documents Act (PIPEDA) — governs privacy and electronic documents",
            "Competition Act — governs competition law and anti-competitive practices",
            "Canadian Consumer Product Safety Act — governs product safety and recalls",
            "Sale of Goods Acts (varies by province) — governs contracts for sale of goods",
            "Commercial Arbitration Acts — governs arbitration in each province",
            "Canada Anti-Spam Legislation (CASL) — governs commercial electronic messages",
        ],
    },
    "DE": {
        "name": "Germany",
        "legislations": [
            "German Civil Code (BGB) — governs contracts, obligations, and civil liability",
            "German Commercial Code (HGB) — governs commercial transactions and business dealings",
            "Act Against Unfair Competition (UWG) — protects against unfair competitive practices",
            "Federal Data Protection Act (BDSG) — governs processing of personal data alongside GDPR",
            "GmbH Act — governs limited liability companies (GmbH)",
            "Stock Corporation Act (AktG) — governs public limited companies (AG)",
            "German Arbitration Act — governs domestic and international arbitration",
            "Product Liability Act — governs liability for defective products",
        ],
    },
    "FR": {
        "name": "France",
        "legislations": [
            "French Civil Code (Code Civil) — governs contracts, obligations, and civil law",
            "French Commercial Code (Code de Commerce) — governs commercial transactions",
            "Consumer Code (Code de la Consommation) — governs consumer rights and protections",
            "Data Protection Act (Loi Informatique et Libertés) — governs data privacy alongside GDPR",
            "Commercial Companies Code — governs formation and management of companies",
            "Labour Code (Code du Travail) — governs employment relationships",
            "Intellectual Property Code — governs copyright, patents, and trademarks",
            "Mediation Act — governs mediation for civil and commercial disputes",
        ],
    },
    "JP": {
        "name": "Japan",
        "legislations": [
            "Japanese Civil Code — governs contracts, obligations, and civil law",
            "Companies Act — governs formation, management, and dissolution of companies",
            "Commercial Code — governs commercial transactions and business dealings",
            "Act on the Protection of Personal Information (APPI) — governs data privacy",
            "Unfair Competition Prevention Act — protects against unfair competitive practices",
            "Product Liability Act — governs liability for defective products",
            "Act on Specified Commercial Transactions — governs consumer transactions",
            "Arbitration Act — governs domestic arbitration proceedings",
        ],
    },
    "BR": {
        "name": "Brazil",
        "legislations": [
            "Brazilian Civil Code (Law No. 10.406/2002) — governs contracts, obligations, and civil law",
            "Brazilian Commercial Code — governs commercial transactions",
            "Consumer Defense Code (CDC) — governs consumer rights and protections",
            "Lei Geral de Protecao de Dados (LGPD) — governs data privacy",
            "Corporations Law (Law No. 6.404/1976) — governs corporations and securities",
            "Startup Framework (Law No. 18.264/2021) — governs startups and entrepreneurship",
            "Arbitration Act (Law No. 9.307/1996) — governs arbitration proceedings",
            "Anti-Corruption Act (Law No. 12.846/2013) — governs anti-corruption compliance",
        ],
    },
    "ZA": {
        "name": "South Africa",
        "legislations": [
            "South African Contract Law — based on Roman-Dutch law governs contracts",
            "Companies Act 71 of 2008 — governs company registration and management",
            "Consumer Protection Act 68 of 2008 — governs consumer rights and protections",
            "Protection of Personal Information Act (POPIA) — governs data privacy",
            "National Credit Act 34 of 2005 — governs credit agreements and consumer credit",
            "Electronic Communications and Transactions Act — governs electronic transactions",
            "Arbitration Act 42 of 1965 — governs arbitration proceedings",
            "Competition Act 89 of 1998 — governs competition law and anti-competitive practices",
        ],
    },
    "NG": {
        "name": "Nigeria",
        "legislations": [
            "Nigerian Contract Law — based on English common law governs contracts",
            "Companies and Allied Matters Act (CAMA) 2020 — governs company registration and management",
            "Federal Competition and Consumer Protection Act 2018 — governs competition and consumer protection",
            "Nigeria Data Protection Regulation (NDPR) — governs data privacy",
            "Sale of Goods Act — governs contracts for sale of goods",
            "Arbitration and Mediation Act 2023 — governs arbitration and mediation proceedings",
            "Banks and Other Financial Institutions Act — governs financial institutions",
            "Electronic Transactions Act — governs electronic transactions",
        ],
    },
    "SA": {
        "name": "Saudi Arabia",
        "legislations": [
            "Saudi Arabian Law of Obligations — governs contracts and obligations",
            "Saudi Companies Law — governs formation and management of companies",
            "Saudi Labour Law — governs employment relationships",
            "Anti-Money Laundering Law — governs anti-money laundering compliance",
            "Electronic Transactions Law — governs electronic transactions and signatures",
            "Personal Data Protection Law — governs data privacy",
            "Saudi Arbitration Law — governs arbitration proceedings",
            "Commercial Court Regulations — governs commercial disputes",
        ],
    },
    "KR": {
        "name": "South Korea",
        "legislations": [
            "Korean Civil Act — governs contracts, obligations, and civil law",
            "Commercial Act — governs commercial transactions and business dealings",
            "Act on the Protection of Personal Information (PIPA) — governs data privacy",
            "Fair Trade Act — governs competition and fair trade practices",
            "Framework Act on Commercial Transactions — governs commercial transactions",
            "Korean Arbitration Act — governs arbitration proceedings",
            "Electronic Commerce Act — governs electronic commerce transactions",
            "Contract Act for Consumers — governs consumer contracts",
        ],
    },
    "CN": {
        "name": "China",
        "legislations": [
            "Civil Code of the People's Republic of China — governs contracts, obligations, and civil law",
            "Company Law — governs formation and management of companies",
            "Personal Information Protection Law (PIPL) — governs data privacy",
            "Anti-Unfair Competition Law — governs unfair competitive practices",
            "Foreign Investment Law — governs foreign investment in China",
            "E-Commerce Law — governs electronic commerce transactions",
            "Arbitration Law — governs arbitration proceedings",
            "Anti-Monopoly Law — governs competition law and anti-monopoly practices",
        ],
    },
    "IT": {
        "name": "Italy",
        "legislations": [
            "Italian Civil Code — governs contracts, obligations, and civil law",
            "Italian Commercial Code — governs commercial transactions",
            "Consumer Code (Codice del Consumo) — governs consumer rights",
            "Data Protection Code — governs data privacy alongside GDPR",
            "Consolidated Act on Banking and Finance — governs financial services",
            "Italian Arbitration Act — governs arbitration proceedings",
            "Electronic Transactions Regulation — governs electronic transactions",
            "Industrial Property Code — governs patents, trademarks, and industrial property",
        ],
    },
    "ES": {
        "name": "Spain",
        "legislations": [
            "Spanish Civil Code — governs contracts, obligations, and civil law",
            "Commercial Code — governs commercial transactions",
            "Consolidated Text of the General Law for the Defence of Consumers and Users — governs consumer rights",
            "Organic Law on Data Protection — governs data privacy alongside GDPR",
            "Companies Act — governs formation and management of companies",
            "Arbitration Act — governs arbitration proceedings",
            "Electronic Commerce Act — governs electronic commerce",
            "Competition Law — governs competition and anti-competitive practices",
        ],
    },
    "NL": {
        "name": "Netherlands",
        "legislations": [
            "Dutch Civil Code (Burgerlijk Wetboek) — governs contracts, obligations, and civil law",
            "Dutch Commercial Code — governs commercial transactions",
            "Dutch Consumer Rights Act — governs consumer protections",
            "General Data Protection Regulation (GDPR) implementation — governs data privacy",
            "Dutch Companies Act — governs formation and management of companies",
            "Dutch Arbitration Act — governs arbitration proceedings",
            "Electronic Commerce Act — governs electronic commerce",
            "Competition Act — governs competition law",
        ],
    },
    "CH": {
        "name": "Switzerland",
        "legislations": [
            "Swiss Code of Obligations — governs contracts and commercial law",
            "Swiss Civil Code — governs civil law and personal rights",
            "Federal Act on Data Protection (FADP) — governs data privacy",
            "Federal Act on Unfair Competition — governs unfair competitive practices",
            "Swiss Code of Companies — governs formation and management of companies",
            "Swiss Rules of International Arbitration — governs arbitration",
            "Federal Act on Consumer Protection — governs consumer rights",
            "Electronic Commerce Act — governs electronic commerce",
        ],
    },
    "AU": {
        "name": "Australia",
        "legislations": [
            "Australian Consumer Law (ACL) — governs consumer rights, product safety, and fair trading",
            "Corporations Act 2001 — governs company registration, management, and deregistration",
            "Competition and Consumer Act 2010 — governs competition, consumer protection, and regulatory frameworks",
            "Privacy Act 1988 — governs collection, use, and disclosure of personal information",
            "Electronic Transactions Act 1999 — validates electronic transactions and communications",
            "Sale of Goods Acts (varies by state) — governs contracts for sale of goods",
            "Commercial Arbitration Acts — governs arbitration in each state and territory",
            "Modern Slavery Act 2018 — requires reporting on modern slavery risks in supply chains",
        ],
    },
    "MX": {
        "name": "Mexico",
        "legislations": [
            "Mexican Civil Code — governs contracts and obligations",
            "Commercial Code — governs commercial transactions",
            "Federal Law on Protection of Personal Data — governs data privacy",
            "Consumer Protection Federal Law — governs consumer rights",
            "General Law of Commercial Companies — governs company formation",
            "Arbitration Act — governs arbitration proceedings",
            "Federal Competition Law — governs competition and anti-competitive practices",
            "Electronic Commerce Act — governs electronic transactions",
        ],
    },
    "AR": {
        "name": "Argentina",
        "legislations": [
            "Argentine Civil and Commercial Code — governs contracts and civil/commercial law",
            "Consumer Protection Law No. 24.240 — governs consumer rights",
            "Personal Data Protection Law No. 25.326 — governs data privacy",
            "General Companies Law No. 19.550 — governs company formation",
            "Arbitration Law No. 27 — governs arbitration proceedings",
            "Antitrust Law No. 25.156 — governs competition law",
            "Electronic Commerce Law No. 25.506 — governs electronic transactions",
            "Banking and Financial Transactions Law — governs financial transactions",
        ],
    },
    "EG": {
        "name": "Egypt",
        "legislations": [
            "Egyptian Civil Code — governs contracts and obligations",
            "Egyptian Commercial Code — governs commercial transactions",
            "Consumer Protection Law No. 181 of 2018 — governs consumer rights",
            "Personal Data Protection Law No. 151 of 2020 — governs data privacy",
            "Companies Law No. 159 of 1981 — governs company formation",
            "Arbitration Law No. 27 of 1994 — governs arbitration proceedings",
            "Competition Law No. 3 of 2005 — governs competition and anti-competitive practices",
            "Electronic Signature Law No. 175 of 2018 — governs electronic transactions",
        ],
    },
    "PH": {
        "name": "Philippines",
        "legislations": [
            "Civil Code of the Philippines — governs contracts and obligations",
            "Corporation Code of the Philippines — governs company formation",
            "Consumer Act of the Philippines (RA 7394) — governs consumer rights",
            "Data Privacy Act of 2012 (RA 10173) — governs data privacy",
            "E-Commerce Act of 2000 (RA 8792) — governs electronic transactions",
            "Foreign Investments Act — governs foreign investment in the Philippines",
            "Arbitration Law (RA 876) — governs arbitration proceedings",
            "Competition Act (RA 10667) — governs competition law",
        ],
    },
    "MY": {
        "name": "Malaysia",
        "legislations": [
            "Contracts Act 1950 — governs contracts and obligations",
            "Companies Act 2016 — governs company formation and management",
            "Consumer Protection Act 1999 — governs consumer rights",
            "Personal Data Protection Act 2010 (PDPA) — governs data privacy",
            "Sale of Goods Act 1957 — governs contracts for sale of goods",
            "Arbitration Act 2005 — governs arbitration proceedings",
            "Competition Act 2010 — governs competition and anti-competitive practices",
            "Electronic Commerce Act 2006 — governs electronic transactions",
        ],
    },
    "TH": {
        "name": "Thailand",
        "legislations": [
            "Thai Civil and Commercial Code — governs contracts and obligations",
            "Thai Labour Protection Act — governs employment relationships",
            "Consumer Protection Act — governs consumer rights",
            "Personal Data Protection Act B.E. 2562 (2019) — governs data privacy",
            "Thai Act on Electronic Transactions — governs electronic transactions",
            "Foreign Business Act — governs foreign business operations",
            "Thai Arbitration Act — governs arbitration proceedings",
            "Trade Competition Act — governs competition and anti-competitive practices",
        ],
    },
    "VN": {
        "name": "Vietnam",
        "legislations": [
            "Civil Code 2015 — governs contracts and obligations",
            "Enterprise Law 2020 — governs company formation and management",
            "Law on Consumer Protection — governs consumer rights",
            "Personal Data Protection Decree No. 13/2023 — governs data privacy",
            "Law on Electronic Transactions — governs electronic transactions",
            "Law on Investment — governs foreign investment in Vietnam",
            "Law on Commercial Arbitration — governs arbitration proceedings",
            "Competition Law — governs competition and anti-competitive practices",
        ],
    },
    "ID": {
        "name": "Indonesia",
        "legislations": [
            "Indonesian Civil Code — governs contracts and obligations",
            "Company Law No. 40 of 2007 — governs company formation",
            "Consumer Protection Law No. 8 of 1999 — governs consumer rights",
            "Personal Data Protection Law No. 27 of 2022 — governs data privacy",
            "Electronic Information and Transactions Law — governs electronic transactions",
            "Investment Law — governs foreign investment in Indonesia",
            "Arbitration Law No. 30 of 1999 — governs arbitration proceedings",
            "Competition Law No. 5 of 1999 — governs competition law",
        ],
    },
    "PK": {
        "name": "Pakistan",
        "legislations": [
            "Contract Act, 1872 — governs contracts and obligations",
            "Companies Act, 2017 — governs company formation and management",
            "Consumer Protection Act, 2005 — governs consumer rights",
            "Personal Data Protection Bill — governs data privacy",
            "Sale of Goods Act, 1930 — governs contracts for sale of goods",
            "Arbitration Act, 2011 — governs arbitration proceedings",
            "Competition Act, 2010 — governs competition and anti-competitive practices",
            "Electronic Transactions Ordinance, 2002 — governs electronic transactions",
        ],
    },
    "BD": {
        "name": "Bangladesh",
        "legislations": [
            "Contract Act, 1872 — governs contracts and obligations",
            "Companies Act, 1994 — governs company formation and management",
            "Consumer Rights Protection Act, 2009 — governs consumer rights",
            "Digital Security Act, 2018 — governs digital security and cybercrime",
            "Sale of Goods Act, 1930 — governs contracts for sale of goods",
            "Arbitration Act, 2001 — governs arbitration proceedings",
            "Competition Act, 2012 — governs competition and anti-competitive practices",
            "Information and Communication Technology Act, 2006 — governs ICT and electronic transactions",
        ],
    },
    "KE": {
        "name": "Kenya",
        "legislations": [
            "Kenya Contract Act — governs contracts and obligations",
            "Companies Act, 2015 — governs company formation and management",
            "Consumer Protection Act, 2012 — governs consumer rights",
            "Data Protection Act, 2019 — governs data privacy",
            "Sale of Goods Act — governs contracts for sale of goods",
            "Arbitration Act, 1995 — governs arbitration proceedings",
            "Competition Act, 2010 — governs competition and anti-competitive practices",
            "Information and Communications Technology Act — governs electronic transactions",
        ],
    },
}


def get_country_config(country_code: str) -> dict[str, str | list[str]] | None:
    return COUNTRIES.get(country_code.upper())


def get_legislation_summary(country_code: str) -> str:
    config = get_country_config(country_code)
    if not config:
        return ""
    laws = config["legislations"]
    return "\n".join(f"- {law}" for law in laws)
